trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '*/target/surefire-reports/TEST-.xml'
      mergeTestResults: true
      testRunTitle: 'Maven Unit Test Results'